<<<<<<< HEAD
# Generated by Django 2.1.2 on 2019-02-21 15:00
=======
# Generated by Django 2.1.2 on 2019-02-22 08:31
>>>>>>> 0e3139fc0ae562fbe41c5ea40a0ac6cc2bc70bc4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedzonkopage',
            name='slug',
<<<<<<< HEAD
            field=models.SlugField(max_length=255, null=True),
=======
            field=models.SlugField(blank=True, max_length=255),
>>>>>>> 0e3139fc0ae562fbe41c5ea40a0ac6cc2bc70bc4
        ),
    ]
