# Generated by Django 2.1.2 on 2019-02-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedzonkopage',
            name='slug',
            field=models.SlugField(max_length=255, blank=True),
        ),
    ]
