# Generated by Django 2.1.2 on 2019-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_jedzonkopage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jedzonkorecipe',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
