# Generated by Django 2.1.2 on 2019-02-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_jedzonkopage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkoplan',
            name='created',
            field=models.DateField(auto_created=True),
        ),
    ]
