# Generated by Django 2.1.2 on 2019-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20190221_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkoplan',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
