# Generated by Django 2.1.2 on 2019-02-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20190221_1605'),
        ('jedzonko', '0003_auto_20190222_1921'),
    ]

    operations = [
    ]
