# Generated by Django 2.1.2 on 2019-02-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_auto_20190221_1608'),
        ('jedzonko', '0003_auto_20190222_1921'),
    ]

    operations = [
    ]
