# Generated by Django 2.1.2 on 2019-02-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_merge_20190223_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jedzonkorecipeplan',
            name='day_name_id',
        ),
        migrations.AddField(
            model_name='jedzonkorecipeplan',
            name='day_name',
            field=models.IntegerField(choices=[(0, 'Poniedzialek'), (1, 'Wtorek'), (2, 'Sroda'), (3, 'Czwartek'), (4, 'Piatek'), (5, 'Sobota'), (6, 'Niedziela')], default=0),
        ),
        migrations.DeleteModel(
            name='JedzonkoDayname',
        ),
    ]
