# Generated by Django 2.1.2 on 2019-02-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_auto_20190223_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jedzonkopage',
            name='slug',
        ),
    ]
