# Generated by Django 2.1.2 on 2019-02-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0008_remove_jedzonkopage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedzonkopage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
