# Generated by Django 2.1.2 on 2019-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0009_jedzonkopage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzonkorecipeplan',
            name='day_name',
            field=models.IntegerField(choices=[(0, 'Poniedzialek'), (1, 'Wtorek'), (2, 'Sroda'), (3, 'Czwartek'), (4, 'Piatek'), (5, 'Sobota'), (6, 'Niedziela')], null=True),
        ),
    ]
